- id: check-trailing-whitespace
  name: Check for trailing whitespace (check only)
  entry: bash -c 'if grep -n "[[:space:]]\+$" "$@"; then echo "Trailing whitespace found!"; exit 1; fi' --
  language: system
  types: [text]

- id: check-end-of-file
  name: Check for end-of-file newline (check only)
  entry: bash -c 'for f in "$@"; do if [ -n "$(tail -c1 "$f" 2>/dev/null)" ]; then echo "Missing EOF newline!"; exit 1; fi; done' --
  language: system
  types: [text]

- id: check-mixed-line-ending
  name: Check for mixed line endings (check only)
  entry: bash -c 'if file "$@" | grep -q CRLF; then echo "Mixed line endings found!"; exit 1; fi' --
  language: system
  types: [text]

- id: check-byte-order-marker
  name: Check for BOM (check only)
  entry: bash -c 'if grep -q $"\xEF\xBB\xBF" "$@"; then echo "BOM found!"; exit 1; fi' --
  language: system
  types: [text]

- id: validate-schema
  name: Validate Database Schema (Multi-Dialect)
  description: Validates database schema files for compliance with RDBMS dialects and naming conventions
  entry: validate-schema
  language: python
  types: [json]
  require_serial: true
  additional_dependencies: [case-converter]

- id: setup-configs
  name: Download shared config files
  description: Downloads shared configuration files from remote repository to local workspace
  entry: bash
  language: system
  pass_filenames: false
  args:
    - -c
    - |
      curl -s https://raw.githubusercontent.com/Hernan-V/pre-commit-check-hooks/main/.sqlfluff_bigquery > .sqlfluff_bigquery
      curl -s https://raw.githubusercontent.com/Hernan-V/pre-commit-check-hooks/main/.isort.cfg > .isort.cfg
      echo "Archivos de configuración descargados: .sqlfluff_bigquery, .isort.cfg"
