repos:
- repo: local
  hooks:
  - id: test-pwd-local
    name: Test PWD Local Hook
    entry: python3 ../test-pwd-hook.py
    language: system
    types: [text]
- repo: /Users/hernanvalenzuela/Workspace/Projects/CMPC/Cmpc Empresas/pre-commit-hooks
  hooks:
  - id: test-pwd-hook